
FROM node:20-alpine

#Production ENV
ENV NODE_ENV=production

#Working DIR
WORKDIR /usr/src/app

#Copy package files
COPY package*.json ./

#Install Dependecies
RUN npm ci -

#Copy code
COPY . .

#Change ownership to node for security
RUN chown -R node:node /usr/src/app
USER node

#Open ports 80/3000
EXPOSE 80
EXPOSE 3500

#Start Application
CMD ["node", "server.js"]
